version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes: &app_volumes
      - .:/app
      - bundle:/app/vendor/bundle
      - rails_cache:/app/tmp/cache
      - node_modules:/app/node_modules
    stdin_open: true
    tty: true
volumes:
  bundle:
  rails_cache:
  node_modules: